# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Running tests, returns code coverage report to #{@output_directory}"
  lane :tests do
    scan(
      clean: true,
      code_coverage: true,
      scheme: "Atthelic App",
      output_directory: @output_directory,
      skip_slack: true,
    )
  end
end
